version: '3.5'
services:
     
    ui:
        image: yeasy/simple-web:latest #VERSION
        networks:
          - frontend
        labels:  
          - "traefik.enable=true"
          - "traefik.http.routers.ui.rule=HostRegexp(`{any:.+}`)"
          - "traefik.http.services.ui.loadbalancer.server.port=80"
          - "discoveryzone=frontend"
        environment:
          JAEGER_AGENT_HOST: "jaeger"
          JAEGER_AGENT_PORT: "6831"

networks:
    frontend:
        name: frontend
        external: true 


