version: '3.5'
services:
     


    ui:
        image: yeasy/simple-web:latest
        networks:
          - frontend
        labels:  
          - "traefik.enable=true"
          - "traefik.http.routers.ui.rule=HostRegexp(`{any:.+}`)"
          - "traefik.http.services.ui.loadbalancer.server.port=80"
          - "discoveryzone=frontend"

networks:
    frontend:
        name: frontend
        external: true 


