defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
    address = ":3000"


[log]
  filePath = "/var/log/traefik.log"

[accessLog]
  filePath = "/var/log/access.log"


[api]
  dashboard = true
  insecure = true

[retry]
attempts = 3
maxMem = 3


[http.middlewares]
  [http.middlewares.test-replacepath.replacePath]
    path = "/api"

[providers.docker]
    constraints = "Label(`discoveryzone`,`frontend`)"


[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
watch = true
exposedbydefault = false
