defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
    address = ":3000"


[log]
  filePath = "/var/log/traefik_backend.log"

[accessLog]
  filePath = "/var/log/access_backend.log"


[api]
  dashboard = true
  insecure = true

[retry]
attempts = 3
maxMem = 3


[providers.docker]
    constraints = "Label(`discoveryzone`,`backend`)"


[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
watch = true
exposedbydefault = false