version: '3.5'
services:
     


    app:
        image: strm/helloworld-http
        networks:
          - backend
        labels:  
          - "traefik.enable=true"
          - "traefik.http.routers.app.rule=HostRegexp(`{any:.+}`)"
          - "traefik.http.services.app.loadbalancer.server.port=80"
          - "discoveryzone=backend"


networks:
    backend:
        name: backend
        external: true 

